### ISSUE TITLE
API Extension: Add getParent in Element

### ISSUE THREAD

**Issue by michaelpisula** [concordion/concordion#101]
Hi,

would it be possible for you to provide a getParent method on org.concordion.api.Element? nu.xom.Element, which you wrap there contains a getParent method (you use it for appendSister), so it should not be a big problem.
If you want, I could provide a pull request for that.

Cheers,
Michael

**Comment by nigelcharman** [comment]
@michaelpisula please confirm this has the expected behaviour, especially that it returns null if getParentElement() is called on the root element or an orphaned element

**Comment by michaelpisula** [comment]
Looks good to me, thanks for the rapid fix :-)
