### ISSUE TITLE
@ExpectedToFail & @Unimplemented on Method Level

### ISSUE THREAD

**Issue by calen-legaspi** [concordion/concordion#113]
In a single fixture, I would like to mark only specific methods as @ExpectedToFail or @Unimplemented. My reason is that a feature or specification will likely evolve over time. When we add or change a scenario to a specification, I would like to mark those new or changed scenarios as failing or unimplemented, but not the others that remain correct. That way Maven/Jenkins doesn't have to fail a build for a new or changed specification, while at the same time regression errors for scenarios that are still valid are caught.

**Comment by nigelcharman** [comment]
Hi, there is currently some experimental work being done on implementing examples as individual JUnit tests. For your use case, would it make more sense to mark specific examples as expected to fail or unimplemented in the specification, or specific methods in the fixture class? 
/cc @drtimwright

**Comment by calen-legaspi** [comment]
Hello, Nigel! Thanks for replying to my issue!

You are right, it would be better if we could mark specific examples as ExpectedToFail or Unimplemented, rather than fixture methods, since sometimes multiple examples use the same fixture method.

**Comment by nigelcharman** [comment]
Hi. Tim has picked this up as part of the work on implementing individual examples as tests. There's some discussion on the concordion-dev list about this. We'll aim to get this into a 1.6.0 release, and will create a snapshot version once @drtimwright thinks it is ready for beta testing.

**Comment by calen-legaspi** [comment]
This is awesome. Thanks! Looking forward to it!

**Comment by nigelcharman** [comment]
This is now implemented as part of the new Example command in the [2.0.0-SNAPSHOT](https://github.com/concordion/concordion/releases/tag/2.0.0-SNAPSHOT) release.

**Comment by calen-legaspi** [comment]
Thanks, Nigel!

Calen
* sent from phone
