### ISSUE TITLE
Cached results not showing successes

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#122]
After running the Concordion specs from `spec.concordion.ConcordionTest`, the elements of `spec/concordion/command/verifyRows/VerifyRows.html` are not highlighted to show success (ie. `class="success"` is not in the output html). If I change:

    ```<a concordion:run="concordion" href="../../command/verifyRows/VerifyRows.html">``` 

to:

    `<a href="../../command/verifyRows/VerifyRows.html">`

in both `VerifyRowsListener.html` and `Listener.html`, the results are highlighted correctly in green.

Have tried with both Eclipse and Gradle and am seeing the same behaviour.

**Comment by nigelcharman** [comment]
@drtimwright - do you have time to look at this?

**Comment by drtimwright** [comment]
Well that is odd. I've reproduced on my machine. I suspect that when results are received from the cache, concordion is re-saving the page - but based on the original HTML. 

Am working on a fix :)

**Comment by drtimwright** [comment]
Pull request created.

**Comment by nigelcharman** [comment]
Thanks for the PR. Is this new with the 2.0 code, or will it be in 
1.5.1? If so, it may be worth a 1.5.2 release - possibly with the 
VerifyRows changes in too.

**Comment by drtimwright** [comment]
I think it was introduced with the example code - that's when I had to move
when the specification was written to disk.

Tim

On 6 September 2015 at 19:08, Nigel Charman <notifications@github.com>
wrote:

> Thanks for the PR. Is this new with the 2.0 code, or will it be in
> 1.5.1? If so, it may be worth a 1.5.2 release - possibly with the
> VerifyRows changes in too.
>
> On 06/09/15 18:42, Tim Wright wrote:
> >
> > Well that is odd. I've reproduced on my machine. I suspect that when
> > results are received from the cache, concordion is re-saving the page
> > - but based on the original HTML.
> >
> > Am working on a fix :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/concordion/concordion/issues/122#issuecomment-138047254
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/concordion/concordion/issues/122#issuecomment-138048885>
> .
>



-- 
Tim
021 251 5593
http://www.linkedin.com/in/drtimwright

**Comment by nigelcharman** [comment]
Sweet. I've realised I could just look at the published 1.5.1 specs 
<http://concordion.org/dist/1.5.1/spec/concordion/command/verifyRows/VerifyRows.html>, 
and it seems to be fine :)

Thanks for the quick fix!

**Comment by nigelcharman** [comment]
Out of interest, where are we going with the JUnit 3 integration? It 
looks pretty basic compared to what you can do with the JUnit 4 integration.

Do you think we should remove or deprecate it in Concordion 2.0?

cheers

**Comment by drtimwright** [comment]
Do people still use jUnit 3?

;)

Tim

On 6 September 2015 at 19:41, Nigel Charman <notifications@github.com>
wrote:

> Out of interest, where are we going with the JUnit 3 integration? It
> looks pretty basic compared to what you can do with the JUnit 4
> integration.
>
> Do you think we should remove or deprecate it in Concordion 2.0?
>
> cheers
>
>
> On 06/09/15 19:24, Tim Wright wrote:
> > I think it was introduced with the example code - that's when I had to
> > move
> > when the specification was written to disk.
> >
> > Tim
> >
> > On 6 September 2015 at 19:08, Nigel Charman <notifications@github.com>
> > wrote:
> >
> > > Thanks for the PR. Is this new with the 2.0 code, or will it be in
> > > 1.5.1? If so, it may be worth a 1.5.2 release - possibly with the
> > > VerifyRows changes in too.
> > >
> > > On 06/09/15 18:42, Tim Wright wrote:
> > > >
> > > > Well that is odd. I've reproduced on my machine. I suspect that when
> > > > results are received from the cache, concordion is re-saving the page
> > > > - but based on the original HTML.
> > > >
> > > > Am working on a fix :)
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/concordion/concordion/issues/122#issuecomment-138047254
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/concordion/concordion/issues/122#issuecomment-138048885
> >
> > > .
> > >
> >
> >
> >
> > --
> > Tim
> > 021 251 5593
> > http://www.linkedin.com/in/drtimwright
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/concordion/concordion/issues/122#issuecomment-138049625
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/concordion/concordion/issues/122#issuecomment-138050557>
> .
>



-- 
Tim
021 251 5593
http://www.linkedin.com/in/drtimwright
