### ISSUE TITLE
Example command causes beforeProcessingSpecification event to be fired to late

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#136]
The Storyboard extension relies on the beforeProcessingSpecification event to provide the 
resource from event.getResource(), unfortunately when running with examples this event is not fired until after the examples have run.

**Event order without example command**
concordionBuilt(final ConcordionBuildEvent event)
beforeProcessingSpecification(final SpecificationProcessingEvent event)
... spec is processed
afterProcessingSpecification(final SpecificationProcessingEvent event)

**Event order with example command**
concordionBuilt(final ConcordionBuildEvent event)
beforeExample(ExampleEvent event)
... spec is processed
afterExample(ExampleEvent event)
beforeProcessingSpecification(final SpecificationProcessingEvent event)
afterProcessingSpecification(final SpecificationProcessingEvent event)

**Comment by nigelcharman** [comment]
I've created a [spec](https://github.com/concordion/concordion/blob/fix-listener-execution-order/src/test/resources/spec/concordion/extension/listener/Listener.html#L102) for this on a new [fix-listener-execution-order](https://github.com/concordion/concordion/tree/fix-listener-execution-order) branch.

Will look to fix it later.

/cc @drtimwright

**Comment by nigelcharman** [comment]
Fixed in 866366f. See specification at http://concordion.github.io/concordion/latest/spec/extension/listener/Listener.html#Example%20with%20examples
