### ISSUE TITLE
Add JUnit5 support

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#141]
It would be useful to start tracking the JUnit 5 development efforts, trialling the new runner and providing feedback to the JUnit project.

From [JUnit Lambda](http://junit.org/junit-lambda.html):

> ## The Vision
> 
> We’ve identified two main areas to focus on during the upcoming JUnit overhaul:
> - Decouple test execution and reporting from test definition and provisioning: This will greatly simplify further evolution of JUnit and allow users to mix test specifications from different test libraries—like JUnit, Spock, ScalaTest and so on—more easily. Other testing libraries should only depend on the test execution/reporting API of JUnit, not on the test definition API (e.g. Runner).
> - Rethinking the JUnit’s extensibility story: Runners, Rules, subclassing and other techniques will be revamped into a cohesive set of constructs to enhance JUnit and to allow—if possible—the seamless combination of individual extensions.
> - Making use of Java 8 features (Lambdas, Streams, Interface default methods) for better assertions, generating test cases, formulating test hierachies, testing asynchronous code and other stuff: We will provide those extensions in additional libraries to keep the JUnit core compatible with older JDKs.
> 
> All development will happen openly on [GitHub](https://github.com/junit-team/junit) in order to foster early feedback and detect problems as soon as possible.

See also [Prototype Writing Test Cases](https://github.com/junit-team/junit-lambda/wiki/Prototype-Writing-Test-Cases)

**Comment by tenwit** [comment]
Is there a schedule for adding java8 support into the Concordion build? I'd like to write a `ConcordionExtension` for JUnit Jupiter, but Jupiter requires java8.

**Comment by nigelcharman** [comment]
Hi, not sure I understand the question. Concordion already supports Java8, and has a Travis CI job to prove it :) 
Are you asking whether we're ready to limit it to Java 8 and remove support for 6 & 7? That could be something we'd look at alongside JUnit Jupiter support. 
If it's possible to implement JUnit Jupiter integration in a separate project, that would be another option, leaving the core build at Java 6.

**Comment by tenwit** [comment]
Ah sorry, I saw `sourceCompatbility = 1.6` in build.gradle and looked no further :)
There's probably no need to drop support for 6 and 7. I know maven profiles and modules make it easy to conditionally build parts of a project; I presume it's easy to do that in gradle too.

**Comment by tenwit** [comment]
Apologies for the massive delay. I've been able to get back to this. I have a design question: what's the best forum for that? It's about choosing between engine and extension, which works better for Concordion and existing users.

**Comment by nigelcharman** [comment]
Best to use the concordion-dev Google Group. I know Tim Wright started looking at this too, so would be good to discuss. thanks.

**Comment by nigelcharman** [comment]
Work is underway in #243

**Comment by nigelcharman** [comment]
Seen on Twitter:

People are already working on their own #JUnit5 engines - here are a few:

* jqwik jqwik.net by @johanneslink
* Specsy specsy.org by  @orfjackal
* Spek spekframework.org by @raniejade, @hhariri et al.
* brahms github.com/sormuras/brahms by @sormuras

**Comment by nigelcharman** [comment]
Also https://github.com/junit-team/junit5/wiki/Third-party-Extensions

**Comment by mwmahlberg** [comment]
Is there any progress on the matter?

**Comment by nigelcharman** [comment]
FYI, there's some good work being done by @lorenzodee on the JUnit 5 implementation, see #345 and #346

**Comment by nigelcharman** [comment]
Thanks for the thorough investigation and comments on the PRs @lorenzodee. 

Just checking the plan:
1. Review and merge #346, test and release as 3.2.0
2. On #345, update our specifications to use new `@ConcordionFixture` annotation, resolve and fix and issues
3. Create and merge a PR to remove JUnit 3 support
4. Review and merge #345, test and release a 4.0.0-SNAPSHOT version
5. Get feedback, make any required changes and release as 4.0.0

Does that sound about right?

For (2), I'd be keen to run our suite multiple times with runners: JUnit 4, JUnit 5 Vintage, JUnit 5 Jupiter. I'm wondering if we could create a meta-annotation or some way of pre-processing the file to use either`@RunWith(ConcordionRunner.class)` or `@ConcordionFixture` dependent on configuration?

I'm hoping to review (1) at the weekend...

**Comment by lorenzodee** [comment]
Yup, that sounds right @nigelcharman.

I'm not aware of a configuration to pre-process and change `@RunWith(ConcordionRunner.class)` to `@ConcordionFixture` and vice-versa. As of the moment, when using JUnit 5 Vintage will keep `@RunWith()` working and help with incremental migration to `@ConcordionFixture`.

I'd be interested in see if there are tools that would auto-magically (or manually configure) use either `@RunWith` or `@ConcordionFixture`.

**Comment by nigelcharman** [comment]
Fixed by #345
