### ISSUE TITLE
Example Command c:status="ExpectedToFail" not working with FailFast annotation

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#144]
Specification is failing when fixture is marked with @FailFast and an exception is thrown

    <div c:example="example3" c:status="ExpectedToFail">
        ...
    </div>

**Comment by nigelcharman** [comment]
Please retest with Concordion [2.0.0-SNAPSHOT](https://github.com/concordion/concordion/releases/tag/2.0.0-SNAPSHOT-20160125).

**Comment by nigelcharman** [comment]
@andrew-sumner - did you get a chance to retest? I'm looking to clear up outstanding issues with 2.0 over the next few days. We should add a spec for this issue either way.

**Comment by andrew-sumner** [comment]
Sorry missed the original email. I'll get right on it.
________________________________
