### ISSUE TITLE
Improve console output when using examples

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#154]
* Improve console output to clearly show Example, Outer and Summary
* If Outer example has no commands, don't print Outer successes and failures to console. Potentially, only run outer example if it has commands in it?
* Revisit the example totals count algorithm

**Comment by nigelcharman** [comment]
@drtimwright - if you have time, would you look at this one please? 

We should maybe move the total counts algorithm into a separate issue. Related is #156, which is about counts when using the parallel runner. The counts never quite matched between parallel and serial, but they are way out now.

**Comment by drtimwright** [comment]
Thinking about "don't print outer example if no successes or failures". Could that apply to any example? (makes the code cleaner if we have few special cases).

**Comment by drtimwright** [comment]
And for the totals, we have two options I can think off this late in the night. We treat example totals like jUnit tests and we report the number of passed test. Or we treat examples like objective-c tests, and report the number of asserts performed.

My preference here is the objective-c model - because (unlike junit) we continue processing a test if an assert fails. But we probably should ask the list.

**Comment by nigelcharman** [comment]
That makes sense. The output will still show it, but it won't show up as 
a test.

**Comment by nigelcharman** [comment]
I think the objective-c model ties into what we have currently. I quite 
like the JUnit tests model, but I think most people would prefer the 
higher numbers.

It gets interesting when using tables. The number of assertions soon 
mounts up, but with the table treated as a single example currently, the 
alternative is 1 result for the whole table. If we use the number of 
assertions, at least the number won't change when we implement each row 
of the table as an example.

Yes, it would be a good list discussion :)

**Comment by nigelcharman** [comment]
See also the discussion at https://groups.google.com/d/msg/concordion/A53L2VHYFsw/IvnEoUSUFgAJ about not calling `beforeExample()` and `afterExample()` for the outer example (or any example which has no commands)

**Comment by nigelcharman** [comment]
Re: "don't print outer example if no successes or failures". 

When using the ParallelRunExtension, the result counts are updated during the afterProcesssingSpecification event. In this case, the outer counts aren't fully known until the specification has finished processing. In order to fix the parallel runner counts (#156), the total counts are now always printed by ConcordionRunner after processing the full specification.

I've remove the printing of outer example counts totally, so that the results now only show counts for actual examples and the full specification. I think this clarifies the output, but keen for feedback.

**Comment by nigelcharman** [comment]
As per Tim's suggestion, I've changed to use objective-c approach.
