### ISSUE TITLE
Exception being written to console when @FailFast annotation is used

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#164]
If we've got fail fast turned on and an exception is throw, this exception is re-thrown at line 171 of the ConcordionRunner class and then something writes the stack trace to the console (I cannot figure out what is doing it).  The previous version of Concordion did not do this so it is an introduced bug.

Concordion is already documenting the error perfectly well so it would be great to stop this message cluttering up my console :-)

**Comment by nigelcharman** [comment]
This originates from the following code added to ConcordionRunner in 5f56cc23

        if (failFastException != null) {
             if (fixtureClass.getAnnotation(FailFast.class) != null) {
                 throw new FailFastException("Failing Fast", failFastException);
             }
         }

I've tried removing this (currently lines 169-173 of ConcordionRunner) and fail-fast still appears to work correctly, including fail-fast on a parent when a child spec fails-fast.

@drtimwright - can you recall whether/why this block of code is needed?

**Comment by drtimwright** [comment]
No idea. It might have been written to get a test to pass but we've since
written code that means this code is redundant.

Tim

On 6 March 2016 at 08:32, Nigel Charman <notifications@github.com> wrote:

> This originates from the following code added to ConcordionRunner in
> 5f56cc2
> <https://github.com/concordion/concordion/commit/5f56cc23ec4d86022db1925b2b1428c9e097d2de>
>
>     if (failFastException != null) {
>          if (fixtureClass.getAnnotation(FailFast.class) != null) {
>              throw new FailFastException("Failing Fast", failFastException);
>          }
>      }
>
> I've tried removing this (currently lines 169-173 of ConcordionRunner) and
> fail-fast still appears to work correctly, including fail-fast on a parent
> when a child spec fails-fast.
>
> @drtimwright <https://github.com/drtimwright> - can you recall
> whether/why this block of code is needed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/concordion/concordion/issues/164#issuecomment-192713300>
> .
>



-- 
Tim
021 251 5593
http://www.linkedin.com/in/drtimwright
