### ISSUE TITLE
ensure String.format() is not used

### ISSUE THREAD

**Issue by ShaKaRee** [concordion/concordion#165]
When cross-compiled to Concordion.NET, String.format() causes performance issues, because it is based on internationalization / culture handling. Therefore SimpleFormatter.format() was implemented using string concatenation.
A verification should be implemented to ensure that String.format() is not used. This could be done by adding a check to the gradle build that fails if usage of String.format() is found.

**Comment by nigelcharman** [comment]
With the cross-compiler being deprecated and a native .NET solution being back in consideration, this is no longer an issue.
