### ISSUE TITLE
Improve exception handing in @Before... and @After... methods

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#166]
From @drtimwright :

If a fixture throws an exception in the @AfterClass method, this happens:
* There are no failures in the output spec
* The test is marked as "throws exception" in any spec that calls c:run on that test
* There is no stacktrace in the spec that has the c:run command

No idea what happens for exceptions thrown in other annotated methods (@After, @AfterSpecification, etc).

**Comment by nigelcharman** [comment]
And from @andrew-sumner :

Changing the index to point to the fixture kind of worked, I got @BeforeSuite event but I'm not always getting the@AfterSuite event - possibly because my test threw an exception and using using @FailFast.

I've got an example in my playpen https://github.com/andrew-sumner/concord of the AfterSuite  not being triggered when exception thrown in BeforeSpecification method

**Comment by drtimwright** [comment]
Hi everyone,

Note that this is for concordion 1.X - I have not tested it in concordion 2
snapshot.

Tim

On 4 February 2016 at 07:58, Nigel Charman <notifications@github.com> wrote:

> From @drtimwright <https://github.com/drtimwright> :
>
> If a fixture throws an exception in the @AfterClass
> <https://github.com/AfterClass> method, this happens:
>
>    - There are no failures in the output spec
>    - The test is marked as "throws exception" in any spec that calls
>    c:run on that test
>    - There is no stacktrace in the spec that has the c:run command
>
> No idea what happens for exceptions thrown in other annotated methods (
> @After <https://github.com/After>, @AfterSpecification, etc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/concordion/concordion/issues/166>.
>



-- 
Tim
021 251 5593
http://www.linkedin.com/in/drtimwright

**Comment by nigelcharman** [comment]
@drtimwright - with the latest 2.0:

When the test is run directly:

* JUnit now shows a test error with the exception message
* the console shows an exception if you use `@AfterSpecification` or `@AfterExample` but not `@AfterClass`
* there is no indication on the spec itself that there was an issue

When the test is run from a parent spec:

* There is no indication of error on JUnit
* the console shows an exception
* the parent spec shows a stack trace

While it would be nice for the error to propogate to the parent spec on JUnit, I think this is adequate for now.

**Comment by nigelcharman** [comment]
@andrew-sumner - have fixed in #181 to always call the `@AfterSuite` annotated method
