### ISSUE TITLE
Concordion execute Fixture different project

### ISSUE THREAD

**Issue by niegus** [concordion/concordion#175]
Hi,

I have one root maven project with multiple modules, and every one of each has its own integration tests.

I've created another module under root which has to have a summary of all the tests in the different modules.

I know there is concordion run command, but I don't know how to refer to the concordion specification html files of the other projects.

    <a concordion:run="concordion" href="pathToOtherProject/Calculator.html">Calculator Service Specifications</a>

Is it possible to do this?

**Comment by nigelcharman** [comment]
Did you find an answer to this?

It's more of a Maven issue than Concordion. 

One suggestion is you could make a dependancy on the test-jar for the other projects (and get the other projects to produce a test-jar). That would at least make the other concordion resources accessible.

**Comment by niegus** [comment]
Yes, I have done the same that you suggested and it works.

I agree with you, it was more a Maven issue than Concordion ;)

Thanks!

**Comment by nigelcharman** [comment]
Thanks for responding. I'll close the issue.
