### ISSUE TITLE
@BeforeExample annotated method executed by "outer specification"

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#187]
I had intended to use it to setup some data before each example, but found I was getting an extra set of data which I realised was from the "outer" example.

It's may be too late to revisit this behaviour but my feeling is that if I wanted to do something outside of the examples I would use @BeforeSpecification and therefore @BeforeExample should only apply to examples.

I think I've been tripped up by this before but I can't remember the situation.  

I know some developers have commented to me that they don't understand why "outer" is showing up in the list of junit tests when they run a specification via eclipse.

**Comment by nigelcharman** [comment]
So the "outer" example is for any commands that are outside of a named example, which are run first.

Would it change things if you had commands outside of the example (including run commands)?

@drtimwright - keen for your thoughts?

Options could be:
1) leave as-is
2) never run methods annotated with `@BeforeExample` or `@AfterExample` around the "outer" example. 
3) determine whether there are any commands in the "outer" example. Remove it as an example if there are no commands in it, so it wouldn't show up on JUnit and `@BeforeExample` or `@AfterExample` would not be run. While this could be confusing if there are run commands in the outer example, at least these should show up with counts in the JUnit results for the "outer" example.

If shown, should we rename the "outer" example to something more explanatory?
