### ISSUE TITLE
Treat table rows as individual examples 

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#207]
Comment from Tim: I've got an idea what the specification would look like for this (basically we have a c:exampleName on a column in the table header) and I don't think it'll be too hard to implement.

**Comment by immo-huneke-zuhlke** [comment]
This is essential in my view. Moreover, like Fit, Concordion should be able to read those tables from Excel files.

**Comment by nigelcharman** [comment]
@immo-huneke-zuhlke thanks for the feedback. This enhancement is something that @drtimwright is actively working on.

Concordion does have an [Excel extension](https://github.com/concordion/concordion-excel-extension) which allows you to use an Excel file as a specification. Would this satisfy your use case?

**Comment by drtimwright** [comment]
I am actively working on it :)

**Comment by immo-huneke-zuhlke** [comment]
Terrific - that's rapid progress (unlike the UK's referendum vote on Thursday!)

I wasn't aware of the Excel extension; that's something I'll look into once I have my pilot project working with Concordion.

To be fair, the Concordion part is working now, after I worked out how to get the background process started and stopped, using a shell script invoked from the Ant Maven plugin. But I'm having real problems with the exchange of XML messages between the test framework and the REST service under test using the JBoss RESTEasy client. I may have to treat the payload as simply a string and use XStream to create/parse payloads.

**Comment by nigelcharman** [comment]
@immo-huneke-zuhlke off-topic, but I recently fixed issue #208 which is that XML characters aren't being automatically escaped when they are specified in Markdown. If you are including XML content in your Markdown spec, the fix for this would be useful to you. The fix is on master, but not yet released.

**Comment by nigelcharman** [comment]
Fixed in 70ff132
