### ISSUE TITLE
Add Set based table comparison

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#21]
_From [garyfros...@gmail.com](https://code.google.com/u/106387411898950830062/) on March 07, 2010 01:53:55_

What steps will reproduce the problem? 1. Create a spec with verifyRows, expect 2 rows, say Value1 and Value2
2. Return results in different order than expected (say Value2, Value1) 3. What is the expected output? What do you see instead? spec will fail

Currently the veryifyRow tag requires a collection with ordered iteration.
 It would be good to allow set based comparison so that order is not important.

_Original issue: http://code.google.com/p/concordion/issues/detail?id=19_

**Comment by calen-legaspi** [comment]
Hi, all!

I'm just curious if this issue being worked on, and if we can expect this to be resolved in the next release?

**Comment by nigelcharman** [comment]
Hi. As far as I know, there is nobody working on this at the moment. Personally, I tend to sort my results in the fixture.

There was some discussion about it on [this thread](https://groups.yahoo.com/neo/groups/concordion/conversations/topics/842).

If you want to have a go at implementing it, I'm happy to provide advice.

**Comment by calen-legaspi** [comment]
Hi, Nigel! Thanks for replying!

Yes, actually I have that on my to-do list - to make that contribution to Concordion. However, just letting you know that I am no longer a developer, as my current role in my organization is in management and sales. :-) I hope to get to it eventually, then again there's are dozens of items in my to-do list that have been ageing there for years! :-(

**Comment by gmandnepr** [comment]
Please review this pull request: https://github.com/concordion/concordion/pull/118

**Comment by gmandnepr** [comment]
Hi Nigel,

Could this be closed after merging #121 ?

**Comment by nigelcharman** [comment]
Thanks to @gmandnepr, this has been implemented in #121, and will be released in Concordion 2.0. See the verify-rows [strategies documentation](http://concordion.github.io/concordion/latest/spec/command/verifyRows/strategies/Strategies.html).
