### ISSUE TITLE
concordion.output.dir property ignored

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [concordion/concordion#213]
The page http://concordion.org/integrations/java/markdown/ states that the output directory for the Concordion reports under Surefire 2.19.1 should be specified as follows:
```
      <configuration>
        <systemPropertyVariables>
          <property>
            <name>concordion.output.dir</name>
            <value>target/concordion</value>
          </property>
        </systemPropertyVariables>
      </configuration>
```
After much experimentation, I eventually discovered that the correct format is
```
      <configuration>
        <systemPropertyVariables>
          <concordion.output.dir>target/concordion</concordion.output.dir>
        </systemPropertyVariables>
      </configuration>
```
Note that it is usually also necessary to specify `includes`, as Surefire defaults won't include fixtures.

**Comment by nigelcharman** [comment]
Thanks for reporting this and making the documentation better for all users :)
