### ISSUE TITLE
Mixing html and markdown in .md file is not working with extensions

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#215]
I'm using the Embed and ExecuteOnlyIf extensions to ignore tests when the environment the tests are running in does not support a particular feature.  This works when the specification is either an html file or pure markdown but due to the limitations of markdown (and the pegdown parser not supporting markdown embedded in html tags) I've had to mix markdown and html to get properly formatted lists.

Mixed html and markdown works fine when isConfigured() returns false, but when it returns true results in the following error message:

**Error Message**

```
14-07-2016 09:57:10.157 INFO  n.g.m.s.datapower.SC901DatapowerTest - Tearing down the acceptance test class SC901DatapowerTest on thread main
[Fatal Error] :5:47: The prefix "ext" for attribute "ext:executeOnlyIf" associated with an element type "ul" is not bound.
Failed to generate breadcrumb: Failed to parse XML document [classpath: /nz/govt/msd/specification/datapower/Datapower.md]
```

**Markdown**

```
# Datapower (DP)

[ ]( - "ext:embed=getNotExecuteReason()")

<div>
       <ul ext:executeOnlyIf="isConfigured()">
              <li><a concordion:run="concordion" href="SC901Datapower.md">MultiDeclaration</a></li>
       </ul>
</div>
```

**Fixture**

```
@RunWith(ConcordionRunner.class)
@Extensions({ EmbedExtension.class, ExecuteOnlyIfExtension.class })
@ConcordionOptions(declareNamespaces = { "ext", "urn:concordion-extensions:2010" })
public class Datapower {
    public boolean isConfigured() {
        return true;
    }

    public String getNotExecuteReason() {
        String msg = "";

        if (!isConfigured()) {
            msg += "<p style=\"background-color: #FFCC99; padding: 8px; border: 1px solid #FF6600; margin: 10px 0px 10px 0px; font-weight: bold\">";
            msg += "WMB is not configured for this environment.";
            msg += "</p>";
        }

        return msg;
    }
}
```

**Example 2**
I've also tried the following mixed markdown and html...

```
# Datapower (DP)

[ ]( - "ext:embed=getNotExecuteReason()")

<div ext:executeOnlyIf="isConfigured()">
  <ul>
    <li><a concordion:run="concordion" href="SC901Datapower.md">MultiDeclaration</a></li>
  </ul>
</div>
```

**Results In**
But get this error:

```
[Fatal Error] :4:140: The element type "li" must be terminated by the matching end-tag "</li>".
Error parsing generated HTML:
<?xml version="1.0" encoding="utf-8" ?>
<html xmlns:concordion='http://www.concordion.org/2007/concordion' xmlns:ext='urn:concordion-extensions:2010'><body><h1>Datapower (DP)</h1>
<p><span ext:embed="getNotExecuteReason()"> </span></p>
<p>&lt;div ext:executeOnlyIf="isConfigured()"&gt; <ul> <li>&lt;a concordion:run="concordion" href="SC901Datapower.md"&gt;MultiDeclaration</a></li> </ul> </div></p></body></html>
```

**Comment by nigelcharman** [comment]
With the error message "Failed to generate breadcrumb:", it looks like the error is happening when Concordion generates the breadcrumbs by parsing the index page in each of the parent packages of the specification being processed.

Does the issue occur when running the SC901Datapower spec in isolation. I suspect it could be caused by the breadcrumb processing on this spec. Please try adding the
 ```
@ConcordionOptions(declareNamespaces = { "ext", "urn:concordion-extensions:2010" })
```
annotation to the SC901Datapower fixture and see if this helps.

**Comment by andrew-sumner** [comment]
Adding @ConcordionOptions(declareNamespaces = { "ext", "urn:concordion-extensions:2010" }) to the called fixture worked fine.

**Comment by nigelcharman** [comment]
Fixed as per https://github.com/concordion/concordion/issues/215#issuecomment-232554498
