### ISSUE TITLE
Floating point numbers in concordion:set

### ISSUE THREAD

**Issue by amanmanocha** [concordion/concordion#234]
concordion:set is failing with exception : 

> java.lang.NumberFormatException: For input string: 

 for floating point numbers.  Following is a small test for reproducing this : 

> <html xmlns:concordion="http://www.concordion.org/2007/concordion">
    <body>
        <p>
            Setting decimal variable <span concordion:set="#a">1.1</span>
            <span concordion:assert-equals="add(#a, #a)">2.2</span>
        </p>
    </body>
</html>

I could not find any other way for using floating point numbers.
Please suggest if am doing anything wrong here.

**Comment by nigelcharman** [comment]
This works OK for me with the following instrumentation:

```
    public float add(float a, float b) {
        return a+b;
    }
```

If it's still an issue for you, would you attach the files for a failing test case? It could be something to do with the encoding of the HTML file.
