### ISSUE TITLE
having access to methods not in class hierarchy of Test Fixture

### ISSUE THREAD

**Issue by abhishek2k9** [concordion/concordion#244]
We have a complex project with over 1000+ java codes. Our HTML specs needs to call methods from multiple Utility / factory classes. Now having all of these methods/classes in one hierarchy is difficult, and has led to a situation where we have a very long class hierarchy.

One approach could be to always call a method in the fixture and in the fixture class have the complexity of deriving the Utility Class and method name. But this leads to having each test fixture have lot of codes, when most of it is common code and should not be in a test fixture, but in a utility class. 

So we would like to have some feature that allows a spec (html) to access a method that is not in the class hierarchy of the test fixture.

Thanks
Abhishek

**Comment by nigelcharman** [comment]
Hi Abhishek, overuse of inheritance is a common "code smell". 

One answer is to [replace inheritance with delegation](https://sourcemaking.com/refactoring/replace-inheritance-with-delegation). This can lead to Java code that is lengthy (which is one reason why people favour inheritance in the first place). 

There are ways of [automatically delegating all methods of a Java class](https://stackoverflow.com/questions/30344715/automatically-delegating-all-methods-of-a-java-class) (for example using Java Proxy, Groovy's `@Delegate` or Lombok's `@Delegate`), or you can use an IDE to auto-generate the methods.

But first consider why your fixtures are so complicated. Review the [Hints and Tips page](http://concordion.org/technique/java/markdown/) and see if there is any way you can simplify your fixtures and isolate behaviours.

Sorry, but the answer isn't to make Concordion specs more complex by calling Java methods from  multiple class files. Our aim is to keep the specs simple and move any complexity into the Java code.
