### ISSUE TITLE
Include "Executable Documentation" plugin

### ISSUE THREAD

**Issue by neuhalje** [concordion/concordion#248]
Concordion is great for writing specs for business people.  It would be even greater if you were able to write documentation for developers as well. E.g. to document libraries or to describe  an API.

I implemented an [extension](https://github.com/neuhalje/concordion-executable-documentation-extension) that
* includes a code formatter for example code ([highlight.js](https://highlightjs.org/))
* can execute the code from the specification (groovy script)
* supports code formatting with ```-blocks (in html and markdown)

<img width="805" alt="screen shot 2017-08-11 at 09 04 58" src="https://user-images.githubusercontent.com/3842066/29203925-40383c24-7e74-11e7-838c-7374b4ce9fae.png">

## Call for Action
If this sounds an interesting extension to concordion, please advise on the code (structure, correct way of doing things). I am willing to move the project over to the concordion github organisation (as long as I retain my commit access :-) )

## Example
The following example as part of a specification would
* format the code
* execute the code
* verify the answer

<pre>
   ```groovy result:#returnValue
   import my.example.Oracle
   
   Oracle oracle = new Oracle();    
   return oracle.answerToLiveTheUniverseAndEverything()
   ```

   This answer is  [42]( - "?=#returnValue") (this check is verified as part of the specification)!
</pre>

* [Source file (markdown)](https://github.com/neuhalje/concordion-executable-documentation-extension/tree/master/src/test/resources/spec/concordion/command/executablespec/ExecutableSpecReturnsValuesMarkdown.md)
* [Fixture](https://github.com/neuhalje/concordion-executable-documentation-extension/tree/master/src/test/groovy/spec/concordion/command/executablespec/ExecutableSpecReturnsValuesMarkdown.groovy)
* [See the result here](https://neuhalje.github.io/concordion-executable-documentation-extension/spec/spec/concordion/command/executablespec/ExecutableSpecReturnsValuesMarkdown.html)

**Comment by nigelcharman** [comment]
Hi Jens,

Thanks for the contribution. We'd be keen to include this in the concordion org and will give you commit rights and attribution. I've invited you to join the concordion org. You should then be able to transfer your repo to concordion.

Can we:
1. rename to `concordion-api-documentation-extension`?
2. change the HTML namespace to a Concordion one (maybe `urn:concordion-extensions:2010` to be consistent with the other extensions, even though it's not 2010 any more :)
3. Maybe change the Java namespace to `org.concordion.ext.apidoc`?

I haven't looked at the code in any detail yet, but will be happy to offer comments on it.

One other thought was whether this should be the concordion-groovy-api-documentation-extension? We could do something similar for Java (and maybe other JVM languages). I'm not sure whether they should be separate extensions or options on this one? I guess one advantage of having them seperate is that a Java based one wouldn't need to include Groovy on the classpath. The downside is duplication of code and features (unless we get smart!).

**Comment by neuhalje** [comment]
Hi Nigel,

that is great! I'm currently implementing 1-3 and will then transfer the project.

Some organisational points (I'll do what is possible for me and raise issues for the rest):

* We need to get travis going (not sure if I can register the project there)
* Same for codecov.io
* Also I think you'll have to include it into jcenter

Regarding Groovy: Good point!  Groovy on the classpath could be an issue, although we only need it on the 'testCompile' path. Although java is not a subset of Groovy it is "if you squint hard enough and accept that we are dealing with example code anyway". That said I am not sure if a java interpreter would be needed (I am a friend of the 80/20 principle).

**Comment by neuhalje** [comment]
Hi Nigel,

I cannot transfer the project: `You don’t have the permission to create repositories on concordion`. Please advise

Cheers
Jens

**Comment by nigelcharman** [comment]
Hi

I've given you permission to create the repository now.

* Travis is easy and one-time so I'm happy to do that once transferred.
* Codecov.io - we don't currently have an account, but can set one up
* JCenter - I'm happy to either do this or send you credentials so you can do this when needed

We do actually have some code in the Concordion project for compiling Java on the fly - see `JavaCompiler`. It would likely need a bunch of methods we might not need with Groovy (eg. `withBoilerplate()`). I'm happy to squint hard enough and just do Groovy to start with :)

**Comment by nigelcharman** [comment]
Hi, looks like things are trucking along. I've requested that the new bintray repo is included in JCenter. Let me know if you need anything else? 
Do you have a real life project using the extension? It would be great to show one off, either linked to from the README and/or on the Concordion blog.

**Comment by neuhalje** [comment]
JCenter will be fun because just this morning I also requested inclusion (https://bintray.com/concordion/maven/concordion-api-documentation-extension) ;-)

My live project will be [bouncy-gpg](https://github.com/neuhalje/bouncy-gpg) (basically an opinionated crypto library that uses bouncycastle as backend). Incidentally I wrote the plugin to create better documentation. As soon as it is ready, I'll add a link.

**Comment by neuhalje** [comment]
Hmm :-(

```text
23:43:06.159 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':bintrayUpload'.
23:43:06.159 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not upload to 'https://api.bintray.com/content/neuhalje/maven/concordion-api-documentation-extension/0.0.4/org/concordion/concordion-api-documentation-extension/0.0.4/concordion-api-documentation-extension-0.0.4.jar?override=1': HTTP/1.1 400 Bad Request [message:Failed to resolve package name]
23:43:06.159 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
```

Any ideas?

**Comment by nigelcharman** [comment]
Should the URL use https://api.bintray.com/content/concordion/maven/ rather than https://api.bintray.com/content/neuhalje/maven/?

I can see the repo at https://bintray.com/concordion/maven/concordion-api-documentation-extension but no versions yet.

**Comment by neuhalje** [comment]
You found it.

For the record:
* I updated to the latest jcenter gradle plugin
* I had to apply this patch to my buildfile

```diff
diff --git a/bintray.gradle b/bintray.gradle
index 32a6d20..c296819 100644
--- a/bintray.gradle
+++ b/bintray.gradle
@@ -74,6 +74,7 @@ bintray {
     pkg {
         repo = 'maven'
         name = 'concordion-api-documentation-extension'
+        userOrg = 'concordion'
         licenses = ['Apache-2.0']
         vcsUrl = 'https://github.com/concordion/concordion-api-documentation-extension.git'
         websiteUrl = 'https://github.com/concordion/concordion-api-documentation-extension'
```
