### ISSUE TITLE
Extensibility support for implementation of aspects for fixture methods

### ISSUE THREAD

**Issue by dadrus** [concordion/concordion#249]
As of today Concordion implements possibilities to implement own Commands and Extensions, which operate on the "specification" level. The extensibility support I would like to have in addition should enable interception of fixture methods called from the specifications. This would enable implementation of different recurring aspects, which could be configured by applying corresponding annotations to required methods.

My concrete project to which this request applies is [jpa-unit](https://github.com/dadrus/jpa-unit). Issue dadrus/jpa-unit#10 discusses the current approach/idea.

**Comment by nigelcharman** [comment]
@dadrus - I suggest we pick up the parts of this that are due to the JUnit Runner in our JUnit5 work - there's some initial exploratory work in #243.

**Comment by dadrus** [comment]
@nigelcharman - Would be cool. But it is not only about the JUnit Runner, it is also about how specification files are resolved. As of today, the corresponding behavior is a fixed part of concordion implementation and relies solely on the class name of the fixture. In my case, since the initial fixture is enhanced at run-time and the corresponding class differs from the original one, there is a need to be able to hook into this specification file name resolution process. Alternatively concordion could implement more logic while resolving specification file names, like coping with enhanced classes etc. From my point of view, the last approach, however, would make things more complex and will probably still have limitations for some use cases. I can draft my idea in a pull request if you like.

**Comment by nigelcharman** [comment]
@dadrus, yes I'd love to see a draft pull request for this. thanks.

**Comment by nigelcharman** [comment]
Released in Concordion 2.1.1

**Comment by dadrus** [comment]
Great! Thank you!
