### ISSUE TITLE
Update run command documentation

### ISSUE THREAD

**Issue by tamasmagyar** [concordion/concordion#254]
http://concordion.org/instrumenting/java/markdown/#run-command

Run command documentation 

Learning from my own experience i think it should include having a runner is must have with the name  (spec, specTest or specFixture) with @RunWith(ConcordionRunner.class) annotation inside the runner.  Otherwise it throws an exception "Unable to find fixture class for".

**Comment by nigelcharman** [comment]
Hi, I've added a sentence to the documentation to clarify. I hope that is sufficient. Adding the actual annotation is problematic since the documentation has to cater for Java, .NET and possibly others (eg. JUnit 5) in future. I hope it is sufficient?

**Comment by tamasmagyar** [comment]
yes, thanks.
