### ISSUE TITLE
Markdown link pointing at .md file not renamed to .html file if the destination fixture throws an error

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion#255]
It's possible that this is related to the FailFast annotation.

_Service.md_
`[Request](Request.md "c:run")`

_Request.md_

*@FailFast*
_RequestFixture.java_

  Does something that throws exception

It’s easy to duplicate with https://github.com/andrew-sumner/cubano-template

Just edit ExampleRestApi and comment out line with TODO above it and run the test suite.

**Comment by nigelcharman** [comment]
Fixed by #263
