### ISSUE TITLE
support for properties in FullOGNL expressions

### ISSUE THREAD

**Issue by vgheo** [concordion/concordion#257]
FullOGNL allows navigation starting with a java object.

If the object is a bean, then OGNL expressions using property names should be allowed.

eg:
    
    [xxx](- "obj.name")

fixture 

    class ExFixture {
         class A {  String getName() { ... }    }
          public A obj;
    }

**Comment by nigelcharman** [comment]
Hi, they are allowed, see [Complex Expressions](https://concordion.github.io/concordion/latest/spec/common/command/expressions/ComplexExpressions.html). `obj` will need to be constructed and you'll need to change visibility of `getName()` to `public`.

**Comment by vgheo** [comment]
I confirm that it works.
Sorry for the noise.
