### ISSUE TITLE
@Aftersuite annotation usage

### ISSUE THREAD

**Issue by HansHofkens** [concordion/concordion#281]
I use the @Aftersuite annotation in my base class to generate a results report. Running the tests from Maven the report is triggered after each spec (. Md) not after the last markdown file is processed. So I have 1.md, 2.md, 3.md etc and I want the report to be triggered after the last md. The @Aftersuite annotation seems ideal but I believe I don't grasp the suite principle in the context of a suite of markdown files. What am I missing? 

This is the structure project>src>test>specs

In this directory I have 1Spec.md and 1SpecFixture.groovy and 2Spec.md and 2SpecFixture.groovy etc.

The POM looks like this:
                                                               
```
<plugin>
<groupId>org.codehaus.mojo</groupId>
<artifactId>build-helper-maven-plugin</artifactId>
<executions>
      <execution>
              <id>add-test-source</id>
              <phase>generate-test-sources</phase>
              <goals>
                       <goal>add-test-source</goal>
              </goals>
              <configuration>
                  <sources>
                     <source>src/test/groovy</source>
                     <source>src/test/specs</source>
                 </sources>
              </configuration>
      </execution>
<execution>
<id>add-test-resource</id>
<phase>generate-test-resources</phase>
<goals>
     <goal>add-test-resource</goal>
 </goals>
 <configuration>
       <resources>
          <resource>
                   <directory>${basedir}/${tests.spec.dir}</directory>
                          <includes>
                                  <include>**/*.md</include>
                          </includes>
          </resource>
       </resources>
       </configuration>
  </execution>
 </executions>
 </plugin>

```

The tests are run using the surefire plugin:

**Comment by nigelcharman** [comment]
So the concept of a suite is that you have a top level specification that uses the [run command](https://concordion.org/instrumenting/java/markdown/#run-command) to run other specifications (which can in turn run other specifications and so on). 

When you run **only** the top level specification, the `@BeforeSuite` and `@AfterSuite` methods will be called on this top level specification, and not on the other specifications that are run using the `run command`.

However, if you run **all** the specifications, you will effectively have multiple suites, with `@BeforeSuite` and `@AfterSuite` methods being called for each specification you run. (Note, Concordion will normally cache the results to stop each being called multiple times).

So you need to make sure that **only** the top level specification is being called from Maven, eg. in the example below, only the `CalculatorFixture` is called:

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.10</version>
        <configuration>
            <systemPropertyVariables>
                <concordion.output.dir>target/concordion</concordion.output.dir>
            </systemPropertyVariables>
            <includes>
                <include>**/CalculatorFixture.java</include>
            </includes>
        </configuration>
    </plugin>

or using Gradle:

    test {
        include '**/CalculatorFixture.*'
        systemProperties['concordion.output.dir'] = "$reporting.baseDir/spec"
    }

**Comment by HansHofkens** [comment]
Ok, I see. Cool a little refactoring required to set up a suite. 

Thanks Nigel
