### ISSUE TITLE
Docs: Missing spec/command/example/Examples.html

### ISSUE THREAD

**Issue by holyjak** [concordion/concordion#288]
The [example command](http://concordion.github.io/concordion/latest/spec/command/example/Examples.html) link at https://concordion.github.io/concordion/latest/spec/specificationType/markdown/Markdown.html leads to 404 Not Found.

**Comment by nigelcharman** [comment]
Thanks for reporting this. I've fixed this instance and created an issue 
to add a link checker to the Travis CI build.
