### ISSUE TITLE
Multi-threaded examples

### ISSUE THREAD

**Issue by shertu** [concordion/concordion#291]
Hello there,

I want to execute a specification and fixture with many examples in a table structure in parallel. Here is an example of the current output we produce:

![image](https://user-images.githubusercontent.com/7973587/64146429-4b7a4f80-ce60-11e9-8c78-920b1e5cece6.png)

These examples could be executed in parallel, however, there does not seem to be any reasonable way to do so any suggestions would be greatly appreciated.

**Comment by nigelcharman** [comment]
Hi, there's no way to run examples in parallel with Concordion currently, and no plans to add this functionality. The parallel run extension allows specifications to be run in parallel.
There was a thought that the introduction of examples in Concordion 2.0 would allow examples to run in parallel. This would require changes to the JUnit integration to enable, which might be easier after we implement JUnit 5 support.
