### ISSUE TITLE
Support pluggable row matching strategies or fix documentation

### ISSUE THREAD

**Issue by krzyv** [concordion/concordion#310]
[Documentation](https://concordion.github.io/concordion/latest/spec/common/command/verifyRows/strategies/Strategies.html) on `verifyRows` strategies mentions non-existing class: `org.concordion.api.RowsMatchStrategy`

Please either make it possible to plug-in custom strategies (preferably) or change documentation, so that it is no longer misleading.

**Comment by nigelcharman** [comment]
Thanks for reporting this. The class was moved to a different package without the documentation being updated. 

The documentation has now been corrected to show the class as `org.concordion.internal.command.strategies.RowsMatchStrategy`.
