### ISSUE TITLE
Markdown tables prefixed with blockquotes are not parsed in concordion 3.0.0 or 3.0.1

### ISSUE THREAD

**Issue by DragosCotoc** [concordion/concordion#312]
Hi Concordion Team,

Currently automating the test scenarios with concordion version 2.2.0 and using the blockquotes in markdown file to have the tables indented.
Notice that in 2.2.0 the markdown files are processed as expected, but when switching to version 3.0.0 or 3.0.1 the tables prefixed with blockquotes are not processed.
Can you please help us with your input regarding this behavior?

Created a small project to highlight the above: https://github.com/DragosCotoc/FunctionalSpecifications/tree/main

Markdown files SpecificationWithBlockquotes.md and SpecificationWithoutBlockquotes.md:
https://github.com/DragosCotoc/FunctionalSpecifications/tree/main/src/test/resources/fixtures

HTML reports SpecificationWithBlockquotes.html and SpecificationWithoutBlockquotes.html:
https://github.com/DragosCotoc/FunctionalSpecifications/tree/main/src/test/resources/results

Thank you and regards,
Dragos

**Comment by nigelcharman** [comment]
Hi Dragos

Thanks for the comprehensive examples which made it easy to reproduce.

We changed the markdown parser in 3.0.0 which has caused a few 
differences with some of the edge cases.

In your case, including the reference style link definitions 
<https://www.markdownguide.org/basic-syntax/#reference-style-links> in 
the blockquotes causes them not to be processed correctly (presumably 
since they are quoted). To correct this, remove the blockquotes from the 
link definition so it reads like:

> ### [Example 1](- "example 1") > > Given the input messages: > >> | 
> [input][][Item][itemIM] | [Message Id][messageIdIM] | [Version 
> Id][versionIdIM] | [Rate][rateIM] | [Quantity][quantityIM] | >> 
> |:-----------------------:|:-------------------------:|:-------------------------:|:--------------:|:----------------------:| 
> >> | 1 | 12355 | 1 | 2 | 100 | >> | 2 | 12356 | 1 | 3 | 200 | >> | 3 | 
> 12357 | 1 | 3 | 0 | >> [input]:- 
> "#inputMsg=generateInputMessage(#{'messageId':#messageId,'versionId':#versionId,'rate':#rate,'quantity':#quantity})" 
> [itemIM]:- "inputMessagesList.add(#inputMsg)" [messageIdIM]:- "#messageId" [versionIdIM]:- "#versionId" [rateIM]:- "#rate" [quantityIM]:- "#quantity" > > When the messages are published [successfully](- 
> "?=publishInputMessages(inputMessagesList)") and [processed](- 
> "processMessages()") > Then [consume](- 
> "#outputMessages=consumeOutputMessages()") the output messages and 
> verify the that the values match the ones from below table: > >> | 
> [output][][Item][itemOM] | [Message Id][messageIdOM] | [Version 
> Id][versionIdOM]] | [Total][totalOM]] | [Status][statusOM]] | >> 
> |:------------------------:|:-------------------------:|:--------------------------:|:-----------------:|:-------------------:| 
> >> | 1 | 12355 | 1 | 200 | PROCESSED | >> | 2 | 12356 | 1 | 600 | 
> PROCESSED | >> | 3 | 12357 | 1 | 0 | UNPROCESSED | >> [output]:- "#outputMsg=getOutputMessage(#outputMessages, #messageId)" [itemOM]:- "#itemOM" [messageIdOM]:- "#messageId" [versionIdOM]:- "?=#outputMsg.getVersionId()" [totalOM]:- "?=#outputMsg.getTotal()" [statusOM]:- "?=#outputMsg.getStatus()"
cheers,
Nigel

**Comment by DragosCotoc** [comment]
Hi @nigelcharman, 

Thank you for your support and for the steps to update the example!

Did the changes and the example is working as expected: tables are indented and the reference links are parsed correctly.

Markdown files WorkingSpecificationWithBlockquotes.md:
https://github.com/DragosCotoc/FunctionalSpecifications/tree/main/src/test/resources/fixtures

HTML reports WorkingSpecificationWithBlockquotes.html:
https://github.com/DragosCotoc/FunctionalSpecifications/tree/main/src/test/resources/results

Thank you and regards,
Dragos
