### ISSUE TITLE
Gradle testCompile is deprecated?

### ISSUE THREAD

**Issue by frankgerhardt** [concordion/concordion#314]
This https://concordion.org/integrations/java/markdown/#gradle suggests

```
dependencies {
  testCompile "org.concordion:concordion:x.y.z"
}
```

but IntelliJ shows that striked out!?

![image](https://user-images.githubusercontent.com/550621/117055748-cbcf1300-ad1b-11eb-8d98-62e49dfa3c2f.png)

Is `testImplementation` the new way?

**Comment by nigelcharman** [comment]
Thanks @frankgerhardt. Fixed by concordion/concordion-website@be1ad10.
