### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by rakesh-sh2020** [concordion/concordion#315]
Hi,

I am looking for a BDD-type solution and doing some due diligence.

I used Concordian many years ago at Sky (2007/2008) time frame and thought it was excellent.

Now I am a mobile dev (Android) looking for something similar to document our apps (reqs in JIRA tickets are too transient and don't live with the codebase).

In the world of mobile there is a new cross-platform solution called Kotlin MultiPlatform Mobile (KMM) which addresses the reusability of business logic across android and ios.

I was considering a tool like Concordian would be a good choice to use for this shared library.

So my question is, is this project actively maintained? Kotlin is the language of KMM and even though it has excellent interop with Java, first class support would be ideal.

Another thing I noticied it that the JUnit 5 PR has been outstanding since 2017.

Any insights you could give as to the suitability of Concordian for my use case would be great.

I would consider helping out as a developer in areas that coincide with my requirements but no promises (yet).

**Comment by nigelcharman** [comment]
Hi

Good to hear from you. Yes, the project is actively maintained.

We don't have a lot of bandwidth for implementing new features currently. JUnit 5 support is likely to be a few weeks work -  the PR was very experimental. Users have found no issues with using the JUnit Vintage engine with JUnit 5.

Having said that, I do have some paid work to add a new feature and will be making a new release in the next few weeks.

I had a user report last week that:

```With Kotlin there is no issue at all. The fixtures work as if they were written in Java. The IntelliJ plugin does not work well but maybe that is not such a big missing feature. It seems to ignore Kotlin editors. And in .md files it does not link to the Kotlin class. We use Gradle with the Kotlin DSL syntax and that was tricky to set up. It took quite some time to configure the paths so that all files were in the right places to be found. ```

I'd be happy to reach out to him to share his insights and we could document those on the website.

And happy for any contributions to the project that you'd consider making.
