### ISSUE TITLE
Add List/Tree data support

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#69]
_From [hanzheng...@gmail.com](https://code.google.com/u/113978170959322930494/) on November 20, 2013 05:14:10_

As we have tabular data verified by #verifyRows , or we can execute commands on a table.

Can we have this kind of data verified the similar(yet more powerful? ) way:

<ul concordion:verifyItems="expr">
    <li>List item one</li>
    <li>List item two with subitems:
        <ul>
            <li>Subitem 1</li>
            <li>Subitem 2</li>
        </ul>
    </li>
    <li>Final list item</li>
</ul>

this is nested list data. which can be very ugly expressed in tabular way ( fixture code maybe ugly too ).

_Original issue: http://code.google.com/p/concordion/issues/detail?id=67_

**Comment by dkatzel-home** [comment]
Should this ticket be closed?  It appears already implemented http://concordion.org/dist/1.5.0/spec/concordion/command/execute/ExecutingList.html

Or is there something else left to do?

**Comment by nigelcharman** [comment]
Thanks Dan. Yes, executing lists was ported to the Java version. Closing this issue.
