### ISSUE TITLE
Support Markdown based specifications

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion#79]
To make it easier for non-technical people to create specifications, allow the specifications to use the Markdown format.

**Comment by dotIN** [comment]
Jinja is very flexible and proven its ability in Python , http://jinja.pocoo.org/2/
Example : Jinja-compatible templating language runtime for Java http://product.hubspot.com/blog/jinjava-a-jinja-for-your-java

**Comment by nigelcharman** [comment]
Fixed by #148
